CREATE TABLE character_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  character_name TEXT NOT NULL,
  character_class TEXT NOT NULL,
  character_spec TEXT NOT NULL,
  character_primary_stat TEXT NOT NULL,
  character_secondary_stat TEXT NOT NULL,
  character_main_stat TEXT NOT NULL
);