CREATE TABLE gear_finder_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE character_list
  ADD COLUMN
    author_id INTEGER REFERENCES gear_finder_users(id)
    ON DELETE SET NULL;
